
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label label2;
	private global::Gtk.Label label1;
	private global::Gtk.Entry nombre;
	private global::Gtk.Entry codigo;
	private global::Gtk.Label label4;
	private global::Gtk.Label label6;
	private global::Gtk.Label label5;
	private global::Gtk.RadioButton radiobutton1;
	private global::Gtk.Label label7;
	private global::Gtk.RadioButton Cuerpo;
	private global::Gtk.RadioButton radiobutton3;
	private global::Gtk.SpinButton opc;
	private global::Gtk.Label label8;
	private global::Gtk.Label label3;
	private global::Gtk.CheckButton checkbutton1;
	private global::Gtk.CheckButton Arg;
	private global::Gtk.CheckButton Mex;
	private global::Gtk.Label label9;
	private global::Gtk.Label label10;
	private global::Gtk.Label label11;
	private global::Gtk.Label label13;
	private global::Gtk.Calendar calendario;
	private global::Gtk.Button button1;
	private global::Gtk.ComboBox Grupo;
	private global::Gtk.Label grupo;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.HeightRequest = 101;
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Codigo");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w1.X = 7;
		w1.Y = 41;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w2.X = 6;
		w2.Y = 7;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.nombre = new global::Gtk.Entry ();
		this.nombre.CanFocus = true;
		this.nombre.Name = "nombre";
		this.nombre.IsEditable = true;
		this.nombre.InvisibleChar = '●';
		this.fixed1.Add (this.nombre);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.nombre]));
		w3.X = 61;
		w3.Y = 5;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.codigo = new global::Gtk.Entry ();
		this.codigo.CanFocus = true;
		this.codigo.Name = "codigo";
		this.codigo.IsEditable = true;
		this.codigo.InvisibleChar = '●';
		this.fixed1.Add (this.codigo);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.codigo]));
		w4.X = 61;
		w4.Y = 36;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("a)");
		this.fixed1.Add (this.label4);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
		w5.X = 21;
		w5.Y = 101;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("c)");
		this.fixed1.Add (this.label6);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label6]));
		w6.X = 337;
		w6.Y = 93;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("b)");
		this.fixed1.Add (this.label5);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label5]));
		w7.X = 204;
		w7.Y = 97;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.radiobutton1 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("de Mexico"));
		this.radiobutton1.CanFocus = true;
		this.radiobutton1.Name = "radiobutton1";
		this.radiobutton1.DrawIndicator = true;
		this.radiobutton1.UseUnderline = true;
		this.radiobutton1.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.fixed1.Add (this.radiobutton1);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.radiobutton1]));
		w8.X = 37;
		w8.Y = 100;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("2.-¿Cuanto es 2+2?");
		this.fixed1.Add (this.label7);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label7]));
		w9.X = 19;
		w9.Y = 148;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Cuerpo = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("del cuerpo"));
		this.Cuerpo.CanFocus = true;
		this.Cuerpo.Name = "Cuerpo";
		this.Cuerpo.DrawIndicator = true;
		this.Cuerpo.UseUnderline = true;
		this.Cuerpo.Group = this.radiobutton1.Group;
		this.fixed1.Add (this.Cuerpo);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Cuerpo]));
		w10.X = 220;
		w10.Y = 96;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.radiobutton3 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("de Guadalajara"));
		this.radiobutton3.CanFocus = true;
		this.radiobutton3.Name = "radiobutton3";
		this.radiobutton3.DrawIndicator = true;
		this.radiobutton3.UseUnderline = true;
		this.radiobutton3.Group = this.radiobutton1.Group;
		this.fixed1.Add (this.radiobutton3);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.radiobutton3]));
		w11.X = 352;
		w11.Y = 93;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.opc = new global::Gtk.SpinButton (0D, 100D, 1D);
		this.opc.CanFocus = true;
		this.opc.Name = "opc";
		this.opc.Adjustment.PageIncrement = 10D;
		this.opc.ClimbRate = 1D;
		this.opc.Numeric = true;
		this.fixed1.Add (this.opc);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.opc]));
		w12.X = 33;
		w12.Y = 166;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("3.-¿De los siguientes paises cuales son de America?");
		this.fixed1.Add (this.label8);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label8]));
		w13.X = 19;
		w13.Y = 192;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("1.-¿ De donde es la pantera rosa?");
		this.fixed1.Add (this.label3);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
		w14.X = 18;
		w14.Y = 77;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.checkbutton1 = new global::Gtk.CheckButton ();
		this.checkbutton1.CanFocus = true;
		this.checkbutton1.Name = "checkbutton1";
		this.checkbutton1.Label = global::Mono.Unix.Catalog.GetString ("España");
		this.checkbutton1.DrawIndicator = true;
		this.checkbutton1.UseUnderline = true;
		this.fixed1.Add (this.checkbutton1);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.checkbutton1]));
		w15.X = 34;
		w15.Y = 214;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Arg = new global::Gtk.CheckButton ();
		this.Arg.CanFocus = true;
		this.Arg.Name = "Arg";
		this.Arg.Label = global::Mono.Unix.Catalog.GetString ("Argentina");
		this.Arg.DrawIndicator = true;
		this.Arg.UseUnderline = true;
		this.fixed1.Add (this.Arg);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Arg]));
		w16.X = 168;
		w16.Y = 216;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Mex = new global::Gtk.CheckButton ();
		this.Mex.CanFocus = true;
		this.Mex.Name = "Mex";
		this.Mex.Label = global::Mono.Unix.Catalog.GetString ("Mexico");
		this.Mex.DrawIndicator = true;
		this.Mex.UseUnderline = true;
		this.fixed1.Add (this.Mex);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Mex]));
		w17.X = 318;
		w17.Y = 216;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("a)");
		this.fixed1.Add (this.label9);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label9]));
		w18.X = 5;
		w18.Y = 218;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("b)");
		this.fixed1.Add (this.label10);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label10]));
		w19.X = 134;
		w19.Y = 216;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("c)");
		this.fixed1.Add (this.label11);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label11]));
		w20.X = 299;
		w20.Y = 217;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label13 = new global::Gtk.Label ();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("4.- Indique la fecha de la independencia de Mexico");
		this.fixed1.Add (this.label13);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label13]));
		w21.X = 28;
		w21.Y = 255;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.calendario = new global::Gtk.Calendar ();
		this.calendario.CanFocus = true;
		this.calendario.Name = "calendario";
		this.calendario.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
		this.fixed1.Add (this.calendario);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.calendario]));
		w22.X = 81;
		w22.Y = 281;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Resultado");
		this.fixed1.Add (this.button1);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button1]));
		w23.X = 460;
		w23.Y = 325;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Grupo = global::Gtk.ComboBox.NewText ();
		this.Grupo.AppendText (global::Mono.Unix.Catalog.GetString ("A"));
		this.Grupo.AppendText (global::Mono.Unix.Catalog.GetString ("B"));
		this.Grupo.AppendText (global::Mono.Unix.Catalog.GetString ("C"));
		this.Grupo.AppendText (global::Mono.Unix.Catalog.GetString ("D"));
		this.Grupo.Name = "Grupo";
		this.fixed1.Add (this.Grupo);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Grupo]));
		w24.X = 292;
		w24.Y = 6;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.grupo = new global::Gtk.Label ();
		this.grupo.Name = "grupo";
		this.grupo.LabelProp = global::Mono.Unix.Catalog.GetString ("Grupo");
		this.fixed1.Add (this.grupo);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.grupo]));
		w25.X = 245;
		w25.Y = 8;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 643;
		this.DefaultHeight = 499;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
	}
}
